#
# Copyright © 2012-2015 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This Gemfile is included by the top-level coopr-provisioner Gemfile
# Any gems added here should be specific to the plugin and not conflict
# with the top-level Gemfile or other plugins

source 'https://rubygems.org'

gem 'fog', '~> 1.36.0'
gem 'fog-profitbricks', '< 2.0' # requires a newer fog 1.42+
gem 'net-ssh', '~> 2.6'

gem 'google-api-client', '~> 0.8.6'
