default['coopr_packages']['debian']['install'] = []
default['coopr_packages']['debian']['upgrade'] = []
default['coopr_packages']['debian']['remove'] = []
default['coopr_packages']['rhel']['install'] = []
default['coopr_packages']['rhel']['upgrade'] = []
default['coopr_packages']['rhel']['remove'] = ['yum-cron']
